<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.example.org/schema/1456140061540" xmlns:tns="http://xmlns.example.com/20160222122101" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ChildAService" targetNamespace="http://xmlns.example.com/20160222122101">
  <wsdl:import namespace="http://www.example.org/schema/1456140061540"/>
  <wsdl:message name="operationRequest">
    <wsdl:part element="extns:operationRequest" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="operationResponse">
    <wsdl:part element="extns:operationResponse" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="operationFault">
    <wsdl:part element="extns:operationFault" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="Service">
    <wsdl:operation name="operation">
      <wsdl:input message="tns:operationRequest" name="operationInput"/>
      <wsdl:output message="tns:operationResponse" name="operationOutput"/>
      <wsdl:fault message="tns:operationFault" name="Fault"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
